
model_type: complete.regression
model_name: nbeats
prediction_type: quantile

predicted_columns: null # list of column names to be predicted
# get the periods from the data
periods: copy(data.periods)
device: copy(trainer.device)

nbeats:
  temporal_features:  []
  categorical_features: {}
  known_future_features: L[]
  embedding_sizes: {}
  embedding_size: 8

  blocks:
    trend:
      block: NBEATSTrendBlock
      units: 2
      thetas_dim: 4
      num_block_layers: 2
      dropout: 0.1
    seasonal:
      block: NBEATSSeasonalBlock
      units: 2
      num_block_layers: 2
      dropout: 0.1
quantiles: [0.02, 0.1, 0.25, 0.5, 0.75, 0.9, 0.98]
semantic_quantile_map:
  lower: 0.1
  mean: 0.5
  upper: 0.9


optimizer:
  lr: 0.001
  weight_decay: 1.e-4
  amsgrad: True

metric:
  module: model.metric.bundle.regression.quantile.v0
  time_modes: ['past', 'future']
  loss_weight:
    s1: 1
    root: 1
    log_prob: 1



