
model_type: complete.regression
model_name: deep_ar
prediction_type: base

predicted_columns:  ["tokenPriceUSD"] 
periods:
  # the input period
  input: 128
  output: 12
device: cuda

deep_ar:
  cell_type: GRU
  hidden_size: 20
  rnn_layers:  2
  dropout:  0.2
  static_features:  []
  temporal_features:  []
  categorical_features: {}
  known_future_features: []
  embedding_sizes: {}
  embedding_size: 8
  embedding_paddings:  []
  device : local_copy(device)
  periods: local_copy(periods)
  distribution: NormalDistribution

optimizer:
  lr: 0.001
  weight_decay: 1.e-3
  amsgrad: True

metric:
  module: model.metric.bundle.regression.distribution.v0
  time_modes: ['future']
  loss_weight:
    s1: 1
    root: 1
    log_prob: 1
