version: "3.9"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - ./dbdata/mongodb:/data/db
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - ./dbdata/postgresql:/var/lib/postgresql/data
  ipfs:
     image: ipfs/go-ipfs:v0.7.0
     container_name: "ipfs"
     ports:
       - 4001:4001
       - 5001:5001
       - 8080:8080
     volumes:
       - ./dbdata/ipfs:/data/ipfs/
  mlflow:
      container_name: mlflow
      restart: always
      build:
          context: ./mlflow
          dockerfile: Dockerfile
      ports:
          - 5000:5000
      environment:
          - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
          - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
          - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
          - MLFLOW_S3_ENDPOINT_URL=${MLFLOW_S3_ENDPOINT_URL}
      depends_on:
        - postgres
      entrypoint: ./wait-for-it.sh ${POSTGRES_HOST}:${POSTGRES_PORT} -t 90 -- mlflow server --backend-store-uri postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE} --default-artifact-root s3://${AWS_MLFLOW_BUCKET_NAME}/ -h 0.0.0.0
  s3:
    image: minio/minio:RELEASE.2021-06-14T01-29-23Z
    container_name: s3
    restart: always
    ports:
      - 9000:9000
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
    command:
      server /data
    volumes:
      - ./dbdata/s3:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8501:8501 # for the user streamlit app
      - 8265:8265
      - 8000:8000
      - 8001:8001
      - 7860-7870:7860-7870
      
    shm_size: 30gb
    container_name: backend
    volumes:
      - ./backend:/app
      - ./backend/.brownie:/root/.brownie
      - ./backend/.bittensor:/root/.bittensor


    working_dir: ${MODEL_WDIR}
    env_file: 
      - .env
    deploy:
      resources:
         reservations:
           devices:
           - driver: nvidia
             count: 'all'
             capabilities: [gpu]
    command: bash -c "./scripts/startup.sh; tail -F anything"

  ganache:
    container_name: ganache
    ports: 
      - ${GANACHE_PORT}:${GANACHE_PORT}
    restart: always
    build:
      context: ./ganache/.
    env_file: 
      - .env
    command: bash -c "./scripts/setup.sh"
  
  frontend:
    container_name: frontend
    build:
      context: ./frontend/.
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - './frontend/src:/app/src'
      - './frontend/public:/app/public'
      - './backend/artifacts:/app/src/artifacts'
    ports:
      - 3000:3000
    command: "npm start"


  subtensor:
    container_name: subtensor
    image: opentensorfdn/subtensor:latest
    cpu_count: 2
    mem_limit: 4000000000
    memswap_limit: 8000000000
    ports:
      - "9944:9944"
      - "30333:30333"
      - "9933:9933"
    expose:
      - "9944"
      - "30333"
      - "9933"
    environment:
      - CARGO_HOME=/var/www/node-subtensor/.cargo
    command: bash -c "/usr/local/bin/node-subtensor --base-path /root/.local/share/node-subtensor/ --chain /subtensor/specs/nakamotoSpecRaw.json --rpc-external --ws-external --rpc-cors all --no-mdns --ws-max-connections 10000 --in-peers 500 --out-peers 500"




  # kafka:
  #   image: "bitnami/kafka:2"
  #   logging:
  #     driver: none
  #   ports:
  #     - "9092:9092"
  #     - "9093:9093"
  #   environment:
  #     - KAFKA_BROKER_ID=1
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
  #     - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
  #     - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
  #     - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
  #   depends_on:
  #     - zookeeper

  # pulsar:
  #   image: apachepulsar/pulsar:2.10.0
  #   ports:
  #     - 8080:8080
  #     - 6650:6650
  #   environment:
  #     PULSAR_MEM: " -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
  #   command: bin/pulsar standalone

  # zookeeper:
  #   image: "bitnami/zookeeper:3.7"
  #   ports:
  #     - "2181:2181"
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes
  #   networks:
  #     - app-tier
  #   logging:
  #     driver: none
