version: "3.9"
services:
  ipfs:
    image: ipfs/go-ipfs:v0.7.0
    container_name: "ipfs"
    ports:
      - 4001:4001 # for the webui
      - 5001:5001 # for the rtc (read/write)
      - 8080:8080 # for the gateway (write)
      
  backend:
    build:
      context: ./backend/ipfsspec
      dockerfile: Dockerfile.fsspec
    container_name: backend
    ports: 
      - 8888:8888 # for the jupyte notebook
    environment:
      - IPFSHTTP_LOCAL_HOST=ipfs
    volumes:
      - ./:/app
    working_dir: /app
    command: bash -c "pip install -e . ;jupyter-lab --ip=0.0.0.0 --no-browser --allow-root"


  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile

    env_file:
      - .env
    volumes:

      - './frontend/src:/app/src'
      - './frontend/public:/app/public'
      - './backend/artifacts:/app/src/artifacts'
    ports:
      - 3000:3000
    command: "npm start"
