model_type: complete.regression
model_name: transformer
prediction_type: distribution

predicted_columns:  ["tokenPriceUSD"] 
periods:
  # the input period
  input: 128
  output: 12
device: cuda

transformer:
  d_model: 16
  attn_heads: 4
  dropout: 0.1
  d_ff: 8
  num_layers: 2
  positional: True
  temporal_features:  []
  categorical_features: {}
  known_future_features: []
  embedding_sizes: {}
  embedding_size: 8

distribution: NormalDistribution

optimizer:
  lr: 0.001
  weight_decay: 1.e-4
  amsgrad: True

metric:
  module: model.metric.bundle.regression.distribution.v0
  time_modes: ['past', 'future']
  loss_weight:
    s1: 1
    root: 1
    log_prob: 1
