module: "model.complete.regression.compose.base"
predicted_columns: null # list of column names to be predicted
# get the periods from the data
periods: copy(data.periods)
batch_size: copy(data.batch_size)
device: copy(trainer.device)

model:
  transformer: get_cfg(model.regression.compose.gp_transformer.base)
  gp: get_cfg(model.regression.compose.gp_transformer.distribution)

metric:
  module: model.metric.bundle.regression.distribution.v0
  time_modes: ['future']
  loss_weight:
    s1: 1
    root: 1
    log_prob: 1