WETH: "https://cryptologos.cc/logos/ethereum-eth-logo.png?v=014"
ETH: "https://cryptologos.cc/logos/ethereum-eth-logo.png?v=014"
WBTC: "https://cryptologos.cc/logos/bitcoin-btc-logo.png?v=014"
BTC: "https://cryptologos.cc/logos/bitcoin-btc-logo.png?v=014"
LINK: "https://cryptologos.cc/logos/chainlink-link-logo.png?v=014"
SHIB: "https://cryptologos.cc/logos/shiba-inu-shib-logo.png?v=014"
AAVE: "https://cryptologos.cc/logos/aave-aave-logo.png?v=014"
SNX: "https://cryptologos.cc/logos/synthetix-network-token-snx-logo.png?v=014"
MATIC: "https://cryptologos.cc/logos/polygon-matic-logo.png?v=014"
SUSHI: "https://cryptologos.cc/logos/sushiswap-sushi-logo.png?v=014"
UMA: "https://cryptologos.cc/logos/uma-uma-logo.png?v=022"
ANKR: "https://cryptologos.cc/logos/ankr-ankr-logo.png?v=022"